FROM python:3.11.10-slim-bookworm

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh

WORKDIR /app

COPY mechanic/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt fastapi uvicorn requests

COPY mechanic/ ./mechanic/

CMD ["python", "mechanic/main.py"]