services:
  mechanic:
    build:
      context: .
      dockerfile: Dockerfile.mechanic
    container_name: pitcrew-mechanic
    user: root 
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pitcrew-net

  payment-gateway:
    build:
      context: ./victim-app
      dockerfile: Dockerfile
    container_name: production-payment-gateway
    ports:
      - "5000:5000"
    labels:
      - "pitcrew.app=payment-gateway"
      - "pitcrew.env=production"
      - "pitcrew.chaos.eligible=true"
    networks:
      - pitcrew-net

networks:
  pitcrew-net:
    driver: bridge